name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install cppcheck -y

    - name: Run cppcheck
      run: cppcheck --enable=all --suppress=missingIncludeSystem --inconclusive --std=c++11 src/

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure CMake
      run: ls -la && cmake .. -G "Unix Makefiles"

    - name: Build project
      run: cd build && make

    - name: Run unit tests
      run: cd tests && ./calculator_unit_tests.exe
