name: Github-hosted Runner

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install cppcheck -y

    - name: Run cppcheck
      run: cppcheck --enable=all --suppress=missingIncludeSystem --inconclusive --std=c++11 src/

    - name: Build
      run: mkdir build && cd build && cmake .. "Unix Makefiles" && make

    - name: Run unit tests
      run: ls -la build/tests && cd build/tests && ./calculator_unit_tests
